apiVersion: v2
publisher: eclipse
name: jupyter
version: 1.0.0
type: Che Editor
displayName:  jupyter
title:  Jupyter Notebook
description:  Jupyter Notebook
icon: 
category: Editor
repository: https://github.com/vdrvergara/che-jupyter-editor
firstPublicationDate: "2021-03-18"
spec:
  endpoints:
   -  name: "jupyter"
      public: true
      targetPort: 8888
      attributes:
        protocol: http
        type: ide
        discoverable: false
        path: /vnc.html?resize=remote&autoconnect=true&reconnect=true
  containers:
   - name: jupyter
     image: "quay.io/che-incubator/che-editor-intellij-community:latest"
     mountSources: true
     env:
         - name: JUPYTER_NOTEBOOK_DIR
           value: /projects
     volumes:
         - mountPath: "/projects"
           name: projects
     ports:
         - exposedPort: 8888
     memoryLimit: "512M"
